sudo: required
addons:
  chrome: stable
language: node_js
nodejs:
  - "node"
  - "lts/*"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run coverage
  - npm run e2e
  - ng build --prod

after_success:
  - codecov
