addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
nodejs:
  - "node"
  - "lts/*"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - ng test --watch="false"
  - npm run e2e
  - ng build --prod --base-href CryptoCalculator

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  local_dir: dist
  on:
    branch:
      master
